version: "3.8"
services:
  runner:
    image: 100xdevs/runner:latest
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - ingress
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
        reservations:
          cpus: "0.2"
          memory: 200M
      labels:
        ingress.host: service_url
        # ingress.host: my-service.replx-dev.oraio.tech
        # ingress.host: my-service.company.tld

networks:
  ingress:
    external: true
    name: ingress-routing
